name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - eslint
          - prettier
          - tsc

    steps:
      - uses: actions/checkout@v3

      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - run: npm i
      - run: npm run lint:${{ matrix.linter }}
